{
 "title": "Kafka Consumer Monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Kafka Consumer Throughput (Rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops/s" } },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_consumed_rate{client_id=~\"consumer-metrics-consumer-group-.*\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Total Records Consumed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_consumed_total{client_id=~\"consumer-metrics-consumer-group-.*\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Kafka Consumer Lag (Current)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_lag{client_id=~\"consumer-metrics-consumer-group-.*\", topic=\"app-metrics\"}",
     "legendFormat": "{{client_id}} - {{topic}} - Partition {{partition}}"
    }
   ]
  },
  {
   "title": "Kafka Consumer Lag (Max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_lag_max{client_id=~\"consumer-metrics-consumer-group-.*\", topic=\"app-metrics\"}",
     "legendFormat": "{{client_id}} - {{topic}}"
    }
   ]
  },
  {
   "title": "Kafka Commit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops/s" } },
   "targets": [
    {
     "expr": "rate(kafka_consumer_coordinator_commit_total{client_id=~\"consumer-metrics-consumer-group-.*\"}[1m])",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Assigned Partitions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_assigned_partitions{client_id=~\"consumer-metrics-consumer-group-.*\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  }
 ]
}