spring:
  application:
    name: metrics-producer-app
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
    properties:
      spring.json.add.type.headers: true
app:
  kafka:
    topic: app-metrics
server:
  port: 9797
