# prometheus.yml
global:
  scrape_interval: 15s # How frequently to scrape targets
  evaluation_interval: 15s # How frequently to evaluate rules

scrape_configs:
  # Job to scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] # Prometheus scrapes its own metrics

  # Job to scrape your metrics-api-app
  - job_name: 'metrics-api-app'
    metrics_path: '/actuator/prometheus' # The endpoint Spring Boot exposes metrics
    static_configs:
      - targets: ['metrics-api-app:5050'] # IMPORTANT: Use the Docker service name and correct internal port (5050)

  # Job to scrape your Producer app
  - job_name: 'metrics-producer-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['metrics-producer-app:9797'] # Docker service name and internal port

  # Job to scrape your Consumer app
  - job_name: 'metrics-consumer-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['metrics-consumer-app:6060'] # Docker service name and UPDATED internal port